[tool.poetry]
name = "mongo-hw"
version = "0.1.0"
description = "my first noSQL db"
authors = ["Fred"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
